### PR TITLE
Style

### PR DESCRIPTION
**Pull request by Abel-desu**
- Understand the concept of state management.
- Use store, actions and reducers in React.
- Connect React and Redux.
- Apply React best practices and language style guides in code.

### CODE REVIEW

**Review by zainsadaqat — CHANGES_REQUESTED** [review]
# Required Changes 🔁
# Hello @Abel-desu  😄 

You're doing a great job on your project. We're proud of you. Good job so far! 

There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights
  ✅  Correct use of Github Flow
  ✅  No linter errors
  ✅  Descriptive Pull Request

## Required Changes ♻️

- [ ] When I try to run the project, It throws the following errors:
-  Module not found: Error: Cannot find file: 'book.js' does not match the corresponding name on disk: './src/redux/books/Redux'.
- Module not found: Error: Cannot find file: 'categories.jsx' does not match the corresponding name on disk: './src/redux/categories/Redux'.
- Module not found: Error: Cannot find file: 'book.js' does not match the corresponding name on disk: './src/redux/books/Redux'.
- Module not found: Error: Cannot find file: 'book.js' does not match the corresponding name on disk: './src/redux/books/Redux'.
- Module not found: Error: Cannot find file: 'configureStore.js' does not match the corresponding name on disk: './src/redux/Redux'.

_Check the comments under the review._




## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding! 👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by arslanbisharat** [comment]
Hi @Abel-desu, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that doesn't have changes after last review. 

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Comment by Abel-desu** [comment]
@[arslanbisharat](https://github.com/arslanbisharat) I talked to my first code reviewer and my project did not have an error that's why I submit it again.  https://www.loom.com/share/74dea38c723f4c0c8c09d2565eade779 also he told me to submit it again.

**Review by MahmoudBakr23 — APPROVED** [review]
Hi @Abel-desu  😃, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit:
Congratulations! 🎉 

**Highlights**
- Great work and effort on this project
- Good communication 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Pull request merged**
